<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Lenovo" name="Beta_Web.Login_Page" tests="7" failures="0" timestamp="2022-01-20T19:14:00 IST" time="32.579" errors="1">
  <testcase name="enterWrongPassword" time="5.406" classname="Beta_Web.Login_Page"/>
  <system-out/>
  <testcase name="enterWrongUsername" time="4.288" classname="Beta_Web.Login_Page"/>
  <system-out/>
  <testcase name="enterBothareWrong" time="4.545" classname="Beta_Web.Login_Page"/>
  <system-out/>
  <testcase name="bothAreEmptyField" time="4.190" classname="Beta_Web.Login_Page"/>
  <system-out/>
  <testcase name="invalidEmailType" time="4.252" classname="Beta_Web.Login_Page">
    <error type="java.lang.Exception" message="Email is Wrong msg is not appears">
      <![CDATA[java.lang.Exception: Email is Wrong msg is not appears
at Beta_Web.Login_Page.invalidEmailType(Login_Page.java:184)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- invalidEmailType -->
  <system-out/>
  <testcase name="submitButton" time="1.922" classname="Beta_Web.Login_Page"/>
  <system-out/>
  <testcase name="correctCredentials" time="7.976" classname="Beta_Web.Login_Page"/>
  <system-out/>
</testsuite> <!-- Beta_Web.Login_Page -->
